clc, clear, close

seq = zeros(99*99,1);
count = 0;
for a = 2:100
    for b = 2:100
        count = count + 1;
        seq(count) = a^b;
    end
end
seq = unique(seq);
sort(seq);
fprintf('There are %d sequence generated by a^b for a=[2,100] b=[2,100]\n',length(seq))
        
        